version: '3.5'
services:
  jenkins:
    image: jenkins:local
    container_name: jenkins
    user: root
    ports:
      - $JENKINS_PORT:8080
      - 50000:50000
    volumes:
      - $JENKINS_HOME:/var/jenkins_home
      - $JENKINS_DATA:/home/jenkins/devops
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_USER=$JENKINS_USER